---
title: "AI Vibrancy EDA"
author: "Taylor Boeckman"
date: "4/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble) 
library(stringr) 
library(tidyverse)
library(treemapify)
library(gridExtra)
library(FactoMineR)
library(factoextra)
library(cluster)
library(ggalt)
library(ggrepel)
library(RColorBrewer)
library(corrplot)
library(ggcorrplot)
```

```{r import-and-clean-data}
aiVibrancyIndicators2019 = read.csv("2019indicators.csv")

aiVibrancyIndicators2019.df <- aiVibrancyIndicators2019

aiVibrancyIndicators2019.tib <- as_tibble(aiVibrancyIndicators2019.df) %>%
  mutate( female_ai_authors = as.double( female_ai_authors ) ) %>%
  mutate( female_ai_skill_penetration = as.double( female_ai_skill_penetration ) ) %>%
  mutate( num_AIpatents = as.double( num_AIpatents ) ) %>%
  mutate( num_AIpatents_pc = as.double( num_AIpatents_pc ) ) %>%
  mutate( num_AIpatent_citation = as.double( num_AIpatent_citation ) ) %>%
  mutate( num_AIpatent_citations_pc = as.double( num_AIpatent_citations_pc ) ) %>%
  mutate( num_AIpatent_references = as.double( num_AIpatent_references ) ) %>%
  mutate( num_AIpatent_references_pc = as.double( num_AIpatent_references_pc ) ) %>%
  mutate( num_AIocc = as.double( num_AIocc ) ) %>%
  mutate( ai_hiring_index = as.double( ai_hiring_index ) ) %>%
  mutate( robot = as.double( robot ) ) %>%
  mutate( male_ai_skill_penetration = as.double (male_ai_skill_penetration) ) %>%
  mutate( num_AIocc_fem = as.double (num_AIocc_fem) ) %>%
  mutate( num_AIocc_male = as.double (num_AIocc_male) ) %>%
  mutate(skill_percentile_rank = as.double( skill_percentile_rank ) )

```

```{r income.group-vis}

aiVibrancyIndicators2019.tib %>%
  count( income.group ) %>%
  mutate( pct = n / sum(n),
          pctlabel = paste0( round( pct*100 ), "%" ) ) %>%
  ggplot( aes( x = reorder( income.group, -pct ),
               y = pct ) ) +
      geom_col( fill = "indianred3",
                color = "black" ) +
      geom_text( aes( label = pctlabel ),
                      vjust = -0.25 ) +
      scale_y_continuous( labels = scales::percent ) +
      labs( x = "Income Group",
            y = "Percent",
            title = "Countries Included on Stanford AI Vibrancy Index By Income Group" )

```

```{r ai_privateinvestment_tot-vis}

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = ai_privateinvestment_tot , y = country ) ) +
      geom_col( fill = "indianred3",
                color = "black" ) +
      facet_wrap( ~ year, ncol = 2) +
      labs( x = "Private Investment in AI",
            y = "Country",
            title = "Private Investment in AI by Country" )

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = ai_privateinvestment_tot_pc , y = country ) ) +
      geom_col( fill = "indianred3",
                color = "black" ) +
      facet_wrap( ~ year, ncol = 2) +
      labs( x = "Private Investment in AI Per Capita",
            y = "Country",
            title = "Private Investment in AI Per Capita by Country" )


```

```{r num_AIconf_papers-vis}

num_AIconf_papers_graph <- aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_papers, y = country, fill = income.group ) ) +
      geom_col() +
      labs( x = "Number of AI Conference Papers",
            y = "Country",
            title = "Number of AI Conference Papers by Country" )

num_AIconf_papers_pc_graph <- aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_papers_pc, y = country, fill = income.group ) ) +
      geom_col() +
      labs( x = "Number of AI Conference Papers Per Capita",
            y = "Country",
            title = "Number of AI Conference Papers  Per Capita by Country" )

grid.arrange(num_AIconf_papers_graph, num_AIconf_papers_pc_graph, ncol = 2)

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_papers, y = country, fill = income.group ) ) +
      geom_col() +
      facet_wrap( ~ year, ncol = 2 ) +
      labs( x = "Number of AI Conference Papers",
            y = "Country",
            title = "Number of AI Conference Papers by Country by Year" )

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_papers_pc, y = country, fill = income.group ) ) +
      geom_col() +
      facet_wrap( ~ year, ncol = 2 ) +
      labs( x = "Number of AI Conference Papers Per Capita",
            y = "Country",
            title = "Number of AI Conference Papers Per Capita by Country by Year" )
```

```{r num_AIconf_citation-vis}

num_AIconf_citation_graph <- aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_citation, y = country ) ) +
      geom_col() +
      labs( x = "Number of AI Conference Citations",
            y = "Country",
            title = "Number of AI Conference Citations by Country" )


num_AIconf_citation_pc_graph <- aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_citation_pc, y = country ) ) +
      geom_col() +
      labs( x = "Number of AI Conference Citations Per Capita",
            y = "Country",
            title = "Number of AI Conference Citations Per Capita by Country" )

grid.arrange(num_AIconf_citation_graph, num_AIconf_citation_pc_graph, ncol = 2)

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_citation, y = country ) ) +
      geom_col() +
      facet_wrap( ~ year, ncol = 2 ) +
      labs( x = "Number of AI Conference Citations",
            y = "Country",
            title = "Number of AI Conference Citations by Country by Year" )
      
aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = num_AIconf_citation_pc, y = country ) ) +
      geom_col() +
      facet_wrap( ~ year, ncol = 2 ) +
      labs( x = "Number of AI Conference Citations Per Capita",
            y = "Country",
            title = "Number of AI Conference Citations Per Capita by Country by Year" )
      
```

```{r female_ai_authors-vis}

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = country , y = female_ai_authors ) ) +
  geom_col( fill = "indianred3",
                color = "black" ) +
  theme(axis.text.x = element_text(angle = 90))

```

```{r female_ai_skill_penetration-vis}

aiVibrancyIndicators2019.tib %>%
  filter(year == "2018") %>%
  ggplot( aes( x = country , y = female_ai_skill_penetration) ) +
  geom_col( fill = "indianred3",
                color = "black" ) +
  theme(axis.text.x = element_text(angle = 90))

```

``` {r startups-vis}

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = country , y = num_AIstartups ) ) +
  geom_col( fill = "indianred3",
                color = "black" ) +
  theme(axis.text.x = element_text(angle = 90))

aiVibrancyIndicators2019.tib %>%
  ggplot( aes( x = country , y = num_AIstartups_pc ) ) +
  geom_col( fill = "indianred3",
                color = "black" ) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r corr-vis}
aiVibrancyNumeric.tib <- aiVibrancyIndicators2019.tib %>%
  select_if( is.numeric ) 

r.mat = cor( aiVibrancyNumeric.tib, use = "complete.obs" )

ggcorrplot( r.mat,
            type = "lower",
            insig = "blank" ) 

```

```{r PAM-pca-analysis-vis}
gower_dist <- daisy( aiVibrancyIndicators2019.tib %>% select( -country ),
                      metric = "gower",
                      type = list( logratio = 3 )
                    ) 

gower.summ <- summary( gower_dist ) 
gower_mat <- as.matrix(gower_dist)

closest.tib <-
aiVibrancyIndicators2019.tib[
        which( gower_mat == min(gower_mat[ gower_mat != min(gower_mat)]),
                arr.ind = TRUE)[1, ], ]

farthest.tib <-
aiVibrancyIndicators2019.tib[
      which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]),
              arr.ind = TRUE)[1, ], ]

k.vec <- 1:15 

get_pam_silwidth <- function( k, dist )
{
  pam.clust <- pam( dist, diss=TRUE, k=k )
  return( pam.clust$silinfo$avg.width )
}

sil_width.vec <- map_dbl( k.vec[ -1 ],
  get_pam_silwidth,
dist=gower_dist
  ) 

pam_sil.tib <- tibble( k = k.vec,
  sil = c( 0, sil_width.vec )
) 

sil_max <- with( pam_sil.tib,
  which( sil == max( sil ) )
) 

pam.clust <- pam( x = gower_dist,
  k = sil_max,
  diss = TRUE
) 

aiVibrancyIndicators2019.tib <- aiVibrancyIndicators2019.tib %>%
    mutate(p3 = factor( paste0( 'p', pam.clust$clustering ) ) )

aiVibrancyIndicators2019_vars.vec <-
  c("country", "num_AIconf_papers","num_AIconf_papers_pc", "num_AIconf_citation", "num_AIconf_citation_pc", "num_AIjournal_papers", "num_AIjournal_papers_pc","num_AIpatents", "num_AIpatents_pc", "ai_privateinvestment_tot", "ai_privateinvestment_tot_pc","num_AIstartups", "num_AIstartups_pc", "female_ai_authors", "female_ai_skill_penetration" )

aiVibrancyIndicators2019.famd <-
  FAMD( aiVibrancyIndicators2019.tib %>% 
          select(all_of(aiVibrancyIndicators2019_vars.vec)), ncp = 6, graph = FALSE ) 

( aiVibrancyIndicators2019.scree.ggplot <- 
  fviz_screeplot( aiVibrancyIndicators2019.famd ) %>%
  labs( title = "Scree Plot") ) 

( aiVibrancyIndicators2019.var.ggplot <-
      fviz_famd_var( aiVibrancyIndicators2019.famd, repel = TRUE ) +
      labs(title = "FAMD Variables Contributions to the Dimensions")) 

aiVibrancyIndicators2019.contrib.dim1.ggplot <-
      fviz_contrib( aiVibrancyIndicators2019.famd, "var", axes = 1,
                    title = "Contribution of vars to Dim-1" )

aiVibrancyIndicators2019.contrib.dim2.ggplot <-
      fviz_contrib( aiVibrancyIndicators2019.famd, "var", axes = 2,
                    title = "Contribution of vars to Dim-2" )

contrib.grid <-
    grid.arrange(aiVibrancyIndicators2019.contrib.dim1.ggplot,
                 aiVibrancyIndicators2019.contrib.dim2.ggplot, nrow = 1,
               top = "Sampled IPs Quality of Representation")


( pam_sil.ggplot <- pam_sil.tib %>%
  ggplot( mapping = aes( x = k, y = sil ) ) +
              geom_line() +
              geom_vline( xintercept = sil_max,
              linetype="dashed", color="blue" ) +
              theme_minimal() +
              scale_x_continuous( breaks = k.vec ) +
              labs( title = "PAM Silhouette Widths" ) +
              ylab( "silhouette width" ) )
```

```{r PAM-clustering-visualization}

aiVibrancyIndicators2019.tib <- aiVibrancyIndicators2019.tib %>%
  mutate( famd_dim1 = aiVibrancyIndicators2019.famd$ind$coord[, 1],
          famd_dim2 = aiVibrancyIndicators2019.famd$ind$coord[, 2]
        ) 

pam_clusters_guide = "PAM\nClusters" 

pam_cluster_colors.vec <- brewer.pal( sil_max, name = "Set1" ) 
names(pam_cluster_colors.vec) <- paste0( 'p', 1:sil_max ) 

quali_ind.tib <- tibble( var  = rownames( aiVibrancyIndicators2019.famd$quali.var$coord ),
                         dim1 = aiVibrancyIndicators2019.famd$quali.var$coord[, 1],
                         dim2 = aiVibrancyIndicators2019.famd$quali.var$coord[, 2]
                       ) 

(aiVibrancyIndicators2019.ggplot <- aiVibrancyIndicators2019.tib %>%
  ggplot( mapping = aes( x = famd_dim1, y = famd_dim2) ) +
    geom_vline( xintercept = 0 ) +
    geom_hline( yintercept = 0 ) +
    geom_point( mapping = aes( color = p3 ), 
                alpha = .5 ) +
    geom_encircle( mapping = aes( group = p3, color = p3 ),
                   linetype = "dotted", s_shape = 0.95 ) +
    theme_minimal() +
    coord_cartesian( xlim = c(-2.5, 20), ylim = c(-5, 15) ) +
    labs( title = "PAM Clusters + FAMD Decomposition" ) )

```
```{r normalize}

normalize <- function(x) { 
  return( ( x - min( x, na.rm = TRUE ) ) / (max(x, na.rm = TRUE ) - min( x, na.rm  = TRUE ) ) ) }

aiVibrancyIndicators2019.tib$num_AIconf_paper_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_papers)

aiVibrancyIndicators2019.tib$num_AIconf_paper_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_papers_pc)

aiVibrancyIndicators2019.tib$num_AIconf_citation_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_citation)

aiVibrancyIndicators2019.tib$num_AIconf_citation_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_citation_pc)

aiVibrancyIndicators2019.tib$num_AIconf_references_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_references)

aiVibrancyIndicators2019.tib$num_AIconf_references_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIconf_references_pc)

aiVibrancyIndicators2019.tib$num_AIjournal_papers_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_papers)


aiVibrancyIndicators2019.tib$num_AIjournal_papers_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_papers_pc)

aiVibrancyIndicators2019.tib$num_AIjournal_citation_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_citation)

aiVibrancyIndicators2019.tib$num_AIjournal_citation_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_citation_pc)

aiVibrancyIndicators2019.tib$num_AIjournal_references_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_references)

aiVibrancyIndicators2019.tib$num_AIjournal_references_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIjournal_references_pc)

aiVibrancyIndicators2019.tib$num_DLpapers_norm <- normalize(aiVibrancyIndicators2019.tib$num_DLpapers)

aiVibrancyIndicators2019.tib$num_DLpapers_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_DLpapers_pc)

aiVibrancyIndicators2019.tib$rca_DLpapers_norm <- normalize(aiVibrancyIndicators2019.tib$rca_DLpapers)

aiVibrancyIndicators2019.tib$skill_percentile_rank_norm <- normalize(aiVibrancyIndicators2019.tib$skill_percentile_rank)

aiVibrancyIndicators2019.tib$enroll_share_norm <- normalize(aiVibrancyIndicators2019.tib$enroll_share)

aiVibrancyIndicators2019.tib$ai_privateinvestment_tot_norm <- normalize(aiVibrancyIndicators2019.tib$ai_privateinvestment_tot)

aiVibrancyIndicators2019.tib$ai_privateinvestment_tot_pc_norm <- normalize(aiVibrancyIndicators2019.tib$ai_privateinvestment_tot_pc)

aiVibrancyIndicators2019.tib$num_AIstartups_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIstartups)

aiVibrancyIndicators2019.tib$num_AIstartups_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIstartups_pc)

aiVibrancyIndicators2019.tib$female_ai_authors_norm <- normalize(aiVibrancyIndicators2019.tib$female_ai_authors)

aiVibrancyIndicators2019.tib$female_ai_skill_penetration_norm <- normalize(aiVibrancyIndicators2019.tib$female_ai_skill_penetration)

aiVibrancyIndicators2019.tib$num_AIpatents_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatents)

aiVibrancyIndicators2019.tib$num_AIpatent_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatents_pc)

aiVibrancyIndicators2019.tib$num_AIpatent_citation_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatent_citation)

aiVibrancyIndicators2019.tib$num_AIpatent_citations_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatent_citations_pc)

aiVibrancyIndicators2019.tib$num_AIpatent_references_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatent_references)

aiVibrancyIndicators2019.tib$num_AIpatent_references_pc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIpatent_references_pc)

aiVibrancyIndicators2019.tib$num_AIocc_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIocc)

aiVibrancyIndicators2019.tib$ai_hiring_index_norm <- normalize(aiVibrancyIndicators2019.tib$ai_hiring_index)

aiVibrancyIndicators2019.tib$robot <- normalize(aiVibrancyIndicators2019.tib$robot)

aiVibrancyIndicators2019.tib$male_ai_skill_penetration_norm <- normalize(aiVibrancyIndicators2019.tib$male_ai_skill_penetration)

aiVibrancyIndicators2019.tib$num_AIocc_fem_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIocc_fem)

aiVibrancyIndicators2019.tib$num_AIocc_male_norm <- normalize(aiVibrancyIndicators2019.tib$num_AIocc_male)

aiVibrancyIndicators2019.tib[aiVibrancyIndicators2019.tib == 1 ] <- NA

(aiVibrancyIndicators2019.tib) #%>% 
  #filter ( country == "United States of America" ) %>%
  #sum( as.numeric(aiVibrancyIndicators2019.tib$num_AIstartups_norm), na.rm = TRUE)
  
```